pipeline {
     agent any

     tools {
        maven 'maven-default'
     }

    stages {
        stage('Checking') {
            when {
                branch "features/*"
            }
            steps {
                script {
                     sh 'mvn verify'
                }
            }
            post {
                always {
                    junit(testResults: '**/surefire-reports/*.xml', allowEmptyResults: true)
                    junit(testResults: '**/failsafe-reports/*.xml', allowEmptyResults: true)
                    jacoco runAlways: true
                }
                //success {
                //    archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false, onlyIfSuccessful: true
                //}
            }
        }
        stage('OtherStage') {
            when {
                branch "features/*"
            }
            steps {
                script {
                    echo 'Stage 2'
                }
            }
        }

         stage('Building') {
            when {
                branch "master"
            }
            steps {
                script {
                     sh 'mvn verify'
                }
            }
            post {
                always {
                    junit(testResults: '**/surefire-reports/*.xml', allowEmptyResults: true)
                    junit(testResults: '**/failsafe-reports/*.xml', allowEmptyResults: true)
                    jacoco runAlways: true
                }
                success {
                    archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false, onlyIfSuccessful: true
                }
            }
         }

         stage('Other Building') {
                when {
                   not {
                       branch 'master'
                   }
               }
                steps {
                    script {
                        echo 'Stage 4'
                    }
              }
         }
         stage('Dockering') {
                 when {
                     branch "master"
                 }
                steps {
                    script {
                        copyArtifacts filter: 'target/*.jar',
                                      fingerprintArtifacts: true,
                                      projectName: '${JOB_NAME}',
                                      flatten: true,
                                      selector: specific('${BUILD_NUMBER}'),
                                      target: 'target';
                        sh 'docker --version'
                        sh 'docker-compose --version'
                        sh 'docker-compose build'
                    }
              }
         }

          stage('Tagging') {
               when {
                   branch "master"
               }
                steps {
                     script {
                        sh 'docker tag msmicroservice msmicroservice:\${env.BUILD_NUMBER}'
                        sh 'docker push msmicroservice:\${env.BUILD_NUMBER}'
                     }
                }
          }
    }
}
