pipeline {
     agent any

     tools {
        maven 'maven-default'
     }

    stages {
        stage('Building') {
            when {
                branch "features/*"
            }
            steps {
                script {
                     sh 'mvn verify'
                }
            }
            post {
                always {
                    junit(testResults: '**/surefire-reports/*.xml', allowEmptyResults: true)
                    junit(testResults: '**/failsafe-reports/*.xml', allowEmptyResults: true)
                    jacoco runAlways: true
                }
                success {
                    archiveArtifacts artifacts: 'target/*.jar', followSymlinks: false, onlyIfSuccessful: true
                    //archiveArtifacts artifacts: 'target/lab04-0.0.1-SNAPSHOT.jar', fingerprint: true, onlyIfSuccessful: true
                }
            }
        }
        stage('Stage 2') {
            when {
                branch "features/*"
            }
            steps {
                script {
                    echo 'Stage 2'
                }
            }
        }

         stage('Stage 3') {
                steps {
                    script {
                        echo 'Stage 3'
                    }
              }
         }

         stage('Stage 4') {
                when {
                   not {
                       branch 'master'
                   }
               }
                steps {
                    script {
                        echo 'Stage 4'
                    }
              }
         }
         stage('Stage 5') {
                steps {
                    script {
                        echo 'Stage 5'
                    }
              }
         }
    }
}
