apiVersion: v1
kind: Service
metadata:
  name: clientes-ppariona
  labels:
    app: lab01
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: lab01
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientes-ppariona
spec:
  selector:
    matchLabels:
      app: lab01
      version: v1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: lab01
        version: v1
    spec:
      containers:
        - name: lab01
          image: mzegarra/java01
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi        
          ports:
            - containerPort: 8080